init plugin

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -1,3 +1,42 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
 set -euo pipefail
 
+if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != "0" ]]
+then
+  echo "--- Skipping git-commit because the command failed"
+  exit 0
+fi
+
+remote=${BUILDKITE_PLUGIN_GIT_COMMIT_REMOTE:-origin}
+branch=${BUILDKITE_PLUGIN_GIT_COMMIT_BRANCH:-${BUILDKITE_BRANCH}}
+message=${BUILDKITE_PLUGIN_GIT_COMMIT_MESSAGE:-"Build #${BUILDKITE_BUILD_NUMBER}"}
+
+if [[ -n ${BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME+x} ]]
+then
+  git config user.name "$BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME"
+fi
+
+if [[ -n ${BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL+x} ]]
+then
+  git config user.email "$BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL"
+fi
+
+if [[ ${BUILDKITE_PLUGIN_GIT_COMMIT_CREATE_BRANCH:-false} = "true" ]]
+then
+  git checkout -b "$branch"
+else
+  git fetch "$remote" "$branch:$branch"
+  git checkout "$branch"
+fi
+git add -A "${BUILDKITE_PLUGIN_GIT_COMMIT_ADD:-.}"
+
+if ! git diff-index --quiet HEAD
+then
+  echo "--- Committing changes"
+  git commit -m "${message}"
+  echo "--- Pushing to origin"
+  git push "$remote" "$branch"
+else
+  echo "--- No changes to commit"
+fi
